include:
  - package:flutter_lints/flutter.yaml
  - package:bloc_lint/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore